
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy JSON Files

on:
  schedule:
    - cron:  '*/60 * * * *'
  repository_dispatch:
    types: [manual_update]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: technote-space/get-diff-action@v1
      id: git_diff
      with:
        PREFIX_FILTER: data
        SUFFIX_FILTER: .json
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        python main.py
    - name: Slack Notification
      # 前Stepの実行結果を判定
      # success() or failure() or always()
      if: failure()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_MESSAGE: 'Error occurred! Please check a log!'
        SLACK_TITLE: ':fire: Data Update Error :fire:'
        SLACK_USERNAME: covid19-scraping
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: deploy
      if: steps.git_diff.outputs.count != 1
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./data
        publish_branch: gh-pages
